import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Roboto, Roboto_Mono } from 'next/font/google'
import '../styles/global.css'

// Define Roboto Sans
const robotoSans = Roboto({
  weight: ['400', '700'], // normal + bold
  subsets: ['latin'],
  variable: '--font-roboto-sans',
})

// Define Roboto Mono
const robotoMono = Roboto_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
  params?: { locale?: string } // accept locale param for localization
}

export default function RootLayout({
  children,
  params,
}: Readonly<RootLayoutProps>) {
  const locale = params?.locale ?? 'en' // fallback to 'en' if no locale

  return (
    <ClerkProvider localization={{ locale }}>
      <html lang={locale}>
        <body className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
